# Generated by Django 5.2.13 on 2026-04-29 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascota',
            old_name='breed',
            new_name='color_pelo',
        ),
        migrations.RenameField(
            model_name='mascota',
            old_name='owner',
            new_name='dueño',
        ),
        migrations.RenameField(
            model_name='mascota',
            old_name='age',
            new_name='edad',
        ),
        migrations.RenameField(
            model_name='mascota',
            old_name='furColor',
            new_name='especie',
        ),
        migrations.RenameField(
            model_name='mascota',
            old_name='furType',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='mascota',
            old_name='weight',
            new_name='peso',
        ),
        migrations.RenameField(
            model_name='mascota',
            old_name='name',
            new_name='raza',
        ),
        migrations.RenameField(
            model_name='mascota',
            old_name='species',
            new_name='tipo_pelo',
        ),
        migrations.RenameField(
            model_name='turno',
            old_name='dateTime',
            new_name='fecha_hora',
        ),
        migrations.RenameField(
            model_name='turno',
            old_name='pet',
            new_name='mascota',
        ),
        migrations.RenameField(
            model_name='turno',
            old_name='reason',
            new_name='motivo',
        ),
        migrations.RenameField(
            model_name='turno',
            old_name='veterinary',
            new_name='veterinaria',
        ),
        migrations.RenameField(
            model_name='veterinaria',
            old_name='address',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='veterinaria',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='veterinaria',
            old_name='phone',
            new_name='telefono',
        ),
        migrations.AlterUniqueTogether(
            name='turno',
            unique_together={('veterinaria', 'fecha_hora')},
        ),
    ]
