# Generated by Django 5.2.15 on 2026-06-15 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0003_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinaria',
            name='horarios',
            field=models.CharField(blank=True, default='Lun-Vie 9:00-19:00', max_length=255),
        ),
        migrations.AddField(
            model_name='veterinaria',
            name='latitud',
            field=models.FloatField(default=-34.6037),
        ),
        migrations.AddField(
            model_name='veterinaria',
            name='longitud',
            field=models.FloatField(default=-58.3816),
        ),
    ]
